// flow-typed signature: 5d5e8490719bce72e4e6d04bbadae75b
// flow-typed version: <<STUB>>/normalize.scss_v^0.1.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.scss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.scss' {
  declare module.exports: any;
}
