// flow-typed signature: 781f4de5f50e1685b1028d760749353d
// flow-typed version: <<STUB>>/normalize.scss_v0.1.0/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.scss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.scss' {
  declare module.exports: any;
}
