// flow-typed signature: 4c50ae1312fca62e44edea49b06ef5b4
// flow-typed version: <<STUB>>/throttle-debounce_v^2.1.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'throttle-debounce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'throttle-debounce' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'throttle-debounce/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'throttle-debounce/dist/index.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'throttle-debounce/dist/index.cjs.js' {
  declare module.exports: $Exports<'throttle-debounce/dist/index.cjs'>;
}
declare module 'throttle-debounce/dist/index.esm.js' {
  declare module.exports: $Exports<'throttle-debounce/dist/index.esm'>;
}
